version: '3.7'

services:
  opensearch2:
    container_name: valet-opensearch_2.5.0
    ports:
      - "9400:9200"
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 8g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    restart: 'always'
    volumes:
      - ./data_2.5.0:/usr/share/opensearch/data